$setup = <<-'SCRIPT' 
sudo apt update
sudo DEBIAN_FRONTEND=noninteractive apt install -y postgresql python3 python3-pip
pip install psycopg2-binary django

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "sf"
  config.vm.provision "shell", inline: $setup
  config.vm.synced_folder "../", "/vagrant"
end